name: Run Tests

on:
  pull_request:
    branches: [main, test-dev-branch]

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21.7.1"

      - name: Install dependencies
        run: |
          cd client
          npm ci
          cd ../server
          npm ci

      - name: Run Cypress tests
        run: |
          cd client
          npm run test:cypress -- --e2e --browser chrome --headless

      - name: Kill server
        working-directory: server
        run: |
          # Find and kill the server process
          SERVER_PID=$(pgrep -f "node server.js")
          if [ -n "$SERVER_PID" ]; then
           kill $SERVER_PID
          fi

      - name: Run Jest tests
        run: |
          cd server
          npm test

      - name: Generate Jest coverage report
        run: |
          cd server
          npx jest --coverage --coverageDirectory=coverage

      - name: Upload Jest coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jest-coverage
          path: server/coverage
