name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: |
          cd client
          npm ci
          cd ../server
          npm ci

      - name: Run Jest tests
        run: |
          cd server
          npm test

      - name: Run Cypress tests
        run: |
          cd client
          npm run test:cypress

      - name: Generate Jest coverage report
        run: |
          cd server
          npm test --coverage

      - name: Generate Cypress coverage report
        run: |
          cd client
          npm run test:cypress --coverage

      - name: Upload Jest coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jest-coverage
          path: server/coverage

      - name: Upload Cypress coverage report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-coverage
          path: client/coverage
